---
- name: Deploy Apache Docker Container
  hosts: target host
  become: yes

  tasks:
    - name: Deploy Apache Docker Container
      docker_container:
        name: apache_container
        image: httpd
        state: started
        ports:
          - "80:80"
        networks:
          - name: my_network
            ipv4_address: 192.168.0.228  

  networks:
    - name: my_network
      driver: bridge
      ipam:
        config:
          - subnet: 172.168.10.0/30
